version: '3.0'

services:
  postgresql_pagarme_db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=pg_nodejs
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
    volumes:
      - 'pg_data:/bitnami/postgresql'

volumes:
  pg_data:
